branch-defaults:
  default:
    environment: udacityudagrameb01-env
environment-defaults:
  udagram-api-dev:
    branch: null
    repository: null
global:
  application_name: udacity-udagram-eb-01
  artifact: ./www/Archive.zip
  default_ec2_keyname: aws-eb
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  deploy: null
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
